Hello microverse
sanamrahimi/-Hello-project pull request #1
Opened 2023-03-21 22:28 UTC by sanamrahimi

## in this pull request, I have implemented features that were mentioned in the requirement.
# Requirements

- Remember to document your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
- Create a new GitHub repo.
- Create a new branch according to the [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) rules.
- Add a .gitignore file.
- Add node_modules to gitignore file.
- Set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config) and make sure that any files that are not relevant are ignored by git.
- Add descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.
- Add 3 files (each one in a separate commit):
- A .html file that includes a header with the text "Hello Microverse!". Use h1 tag for that.
- A .css file that includes one class with styles for your header (make it in your favorite color).
- A test.md file with the text "This file should be ignored by git".
-

2023-03-22 08:56 UTC, AlphaNtihinduka requested changes
## Hi @sanamrahimi 🙋‍♂️
Good job working on your hello Microverse project.  

You still need to implement few on the project but you are almost there!!! :watch: 

TO HIGHLIGHT:
- Your project is professional ✅
- Professional README file :100: 
- Your PR is professional ✅
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

# Required Changes :recycle: 
- _Kindly consider the inline review comments._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-03-22 08:56 UTC, AlphaNtihinduka commented on README.md
> +> Describe your project in 1 or 2 sentences.
- [ ] Kindly consider removing these default statements. Removing them will help us have a professional readme file ☺️.

2023-03-22 08:56 UTC, AlphaNtihinduka commented on README.md
> +> Describe the tech stack and include only the relevant sections that apply to your project.
- [ ] Kindly consider removing these default statements. Removing them will help us have a professional readme file ☺️.

2023-03-22 08:56 UTC, AlphaNtihinduka commented on README.md
> +> Describe between 1-3 key features of the application.
- [ ] Kindly consider removing these default statements. Removing them will help us have a professional readme file ☺️.

2023-03-22 08:56 UTC, AlphaNtihinduka commented on README.md
> +
- [ ] Kindly consider removing these default statements. Removing them will help us have a professional readme file ☺️.

2023-03-22 08:56 UTC, AlphaNtihinduka commented on README.md
> +- **[key_feature_3]**
- [ ] I have noticed that your `key features` is not customized. Kindly ensure to add your project's key features. This helps us to have a professional README file ☺️.

2023-03-22 08:56 UTC, AlphaNtihinduka commented on README.md
> +- [ ] **[new_feature_3]**
- [ ] I have noticed that your `future features` is not customized. Kindly ensure to add your project's future features. This helps us to have a professional README file ☺️.
- [ ] Kindly consider removing these default statements. Removing them will help us have a professional readme file ☺️.

2023-03-22 08:56 UTC, AlphaNtihinduka commented on README.md
> +  - [Answer_2]
- [ ] [OPTIONAL] I have noticed that your `FAQ` is not customized. Kindly ensure to add your project's FAQ. This helps us to have a professional README file ☺️.

2023-03-22 08:56 UTC, AlphaNtihinduka commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] I have noticed that your license link is broken. The MIT license gives users :person_curly_hair:  express permission to reuse code for any purpose. At this stage, it means your project is not yet licensed and hence the code can not be reused. Kindly ensure to add the license file to your project directory ☺️.

2023-03-22 08:56 UTC, AlphaNtihinduka commented on README.md
> +
- [ ] I have noticed that your `support subsection` is not customized. Kindly ensure to add your project's support section. This helps us to have a professional README file ☺️. It also helps to increase the project engagement. In addition, kindly consider removing these default statements. Removing them will help us have a professional readme file ☺️.

2023-03-22 08:56 UTC, AlphaNtihinduka commented on README.md
> +
- [ ] I have noticed that your `acknowledgments` is not customized. Kindly ensure to add your project's acknowledgments. This helps us to have a professional README file ☺️. In addition, kindly consider removing these default statements. Removing them will help us have a professional readme file ☺️.

2023-03-23 21:21 UTC, vickymarz requested changes
Hi @sanamrahimi, 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- I will suggest you use a more descriptive branch name that better describes what changes or features you are working on. Your branch name should be the bane of a feature and not a feature itself


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 21:21 UTC, vickymarz commented on README.md
> +- [📝 License](#license)
- [ ] Please note that the MIT license gives users 🧑‍🦱 express permission to reuse code for any purpose. At this stage, it means your project is not yet licensed and hence the code can not be reused. Kindly ensure to add the license file to your project directory as the previous reviewer suggested.

2023-03-24 07:51 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @sanamrahimi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 08:08 UTC, merged